name: Anchore Scan

on:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Anchore Container Scan
        uses: anchore/scan-action@v2.0.4
        with:
          path: "."
          fail-build: true

